### ISSUE TITLE
Problem on getYValue(...)

### ISSUE THREAD

**Issue by marta312** [szotsaki/LIS331#2]
I found a typo on this function, original version:

    inline uint8_t getYValue(int16_t &ret) {
        return getAxisValue(LIS_OUT_Y_L, LIS_OUT_X_H, ret);
    }

I think it should be

    inline uint8_t getYValue(int16_t &ret) {
        return getAxisValue(LIS_OUT_Y_L, LIS_OUT_Y_H, ret);
    }

Thank you!

**Comment by szotsaki** [comment]
Ahh, well spotted. Thank you, I fixed it and there is a new release with the fix.
